#!/bin/sh
# Give dmenu list of clipboard history to copy.
# Shows the selected character in dunst if running.

# Must have xclip installed to even show menu.
xclip -h >/dev/null || exit

chosen=$(tac ~/.xclip_history | dmenu -i -l 20 -fn "Mono:size=10" -nb "#282828" -nf "#ebdbb2" -sb "#1d2021" -sf "#fe8019")

[ "$chosen" != "" ] || exit

echo "$chosen" | xclip -selection clipboard
echo "$chosen" | xclip

notify-send "'$chosen' copied." &
