#!/usr/bin/env bash
#echo -e "<span foreground='black' background='#01A252' font-style='italic'>txt</span>\n"

extip=$(dig +short myip.opendns.com @resolver1.opendns.com)

case $BLOCK_BUTTON in
    1) pgrep -x dunst >/dev/null && notify-send $extip;;
esac

if $extip ; then
   echo -e "<span foreground='red'></span>\n"
else
    echo -e "<span foreground='green'></span>\n"
fi
