#!/bin/bash

# Take a screenshot
import -window root /tmp/screen.png

pgrep -x dunst && notify-send -i ~/.images/lock.png "Locking computer..." &&

# Create a blur on the shot
convert /tmp/screen.png -paint 1 -swirl 360 /tmp/screen.png

# Compress the image
pngquant --ext .png -f /tmp/screen.png

# Add the lock to the blurred image
[[ -f ~/.images/lock.png ]] && convert /tmp/screen.png  ~/.images/lock.png -gravity center -composite -matte /tmp/screen.png

# Pause music
mpc pause

# Lock it up!
i3lock -e -f -c 000000 -i /tmp/screen.png

# In five seconds, turn off display unless key press in last 4 seconds.
sleep 5 && [ 4000 -lt "$(xssstate -i)" ] &&  pgrep -x i3lock && xset dpms force off
