#!/bin/bash

case $BLOCK_BUTTON in
    1) $TERMINAL -e ncpamixer & disown ;;
    3) pamixer --default-source -t ;;
    4) pamixer --default-source -i 5 ;;
    5) pamixer --default-source -d 5 ;;
esac

printpastatus() { [[ $(pamixer --default-source --get-mute) = "true" ]] && echo -e "<span foreground='red'></span>" && exit
echo  $(pamixer --default-source  --get-volume)% ;}
printpastatus
