#!/bin/bash

printxkbstate() {
    xkblayout-state print %s | awk '{print toupper($0)}'
}

case $BLOCK_BUTTON in
    1) xdotool key Control_L+Super_L ;;
    3) xdotool key Control_L+Super_L ;;
esac

printxkbstate
