#!/bin/bash
sleep 2

# Office LAN
if [[ $(ip addr show dev enp0s25 | sed -n "s/\s.*inet\s//; s/^\([[:digit:]]\+.[[:digit:]]\+.[[:digit:]]\+.[[:digit:]]\+\).*/\1/p") == '10.10.10.103' ]]; then
    xrandr --output VIRTUAL1 --off --output eDP1 --primary --mode 1366x768 --pos 1920x0 --rotate normal --output DP1 --off --output HDMI2 --off --output HDMI1 --off --output DP2 --mode 1920x1080 --pos 0x0 --rotate normal;
    exit;
fi

# Office WiFi
if [[ $(ip addr show dev wlp3s0 | sed -n "s/\s.*inet\s//; s/^\([[:digit:]]\+.[[:digit:]]\+.[[:digit:]]\+.[[:digit:]]\+\).*/\1/p") == '10.10.10.102' ]]; then
    xrandr --output VIRTUAL1 --off --output eDP1 --primary --mode 1366x768 --pos 1920x0 --rotate normal --output DP1 --off --output HDMI2 --off --output HDMI1 --off --output DP2 --mode 1920x1080 --pos 0x0 --rotate normal;
    exit;
fi

exit 0
